import React from 'react';

function About() {
    return (
        <div className='about'>
            <h1>About</h1>
            <p>The Sci-Fi Film Poster Club is a mock NFT project. I (Damon Pickett) built this site to hone my skills in developing front-end interfaces that interact with smart contracts.</p>
            <p>This app allows users to connect their ethereum wallets and purchase NFT’s representing the film poster of their choice.</p>
            <p>Upon purchasing an NFT with RinkeybyETH, the user can then view their NFT on OpenSea’s testnet.</p>
            <p>User’s are limited to 3 NFT’s per poster via their respective smart contract. Each NFT costs 0.01 RinkebyETH.</p>
            <p>As the owner, I am able to withdraw the revenue generated by the contracts.</p>
            <p>The front-end was built with React.js, Ethers.js, and Hardhat. The smart contract was written in Solidity.</p>
            <p>If you have any questions and would like to get in touch with me, please feel free to connect with me on social media via the links below. I can also be contacted through my online portfolio.</p>
        </div>
    )

}

export default About;