import React from 'react';

function About() {
    return (
        <div className='about'>
            <h1>About</h1>
            <p>The Sci-Fi Film Poster Club is a mock NFT project. I (<a href='https://damonpickett.github.io/portfolio/' className='about-links' target='_blank' rel='noreferrer'>Damon Pickett</a>) built this site to hone my skills in developing front-end interfaces that interact with smart contracts.</p>
            <p>This app allows users to connect their ethereum wallets and purchase NFT’s representing the film poster of their choice.</p>
            <p>Upon purchasing an NFT with RinkebyETH, the user can then view their NFT on <a href='https://testnets.opensea.io/' className='about-links' target='_blank' rel='noreferrer'>OpenSea’s testnet</a>.</p>
            <p>Users are limited to 3 NFTs per poster via the respective smart contract. Each NFT costs 0.01 RinkebyETH.</p>
            <p>As the owner, I am able to withdraw the revenue generated by the contracts.</p>
            <p>The front-end was built with React.js, Ethers.js, and Hardhat. The smart contracts use the ERC721 standard and were written in Solidity. The metadata for the NFTs is stored on IPFS.</p>
            <p>If you have any questions and would like to get in touch, please feel free to connect with me on social media via the links below. I can also be contacted through my <a href='https://damonpickett.github.io/portfolio/' className='about-links' target='_blank' rel='noreferrer'>online portfolio</a>.</p>
        </div>
    )

}

export default About;